import React from 'react';
import { useTranslation } from 'react-i18next';
import { HelpCircle, Compass, Radio, ShieldCheck } from 'lucide-react';
import { SafetyDisclaimer } from '../components/common/SafetyDisclaimer';

export const HelpPage: React.FC = () => {
  const { t } = useTranslation();

  return (
    <div className="space-y-6 pb-16 max-w-4xl mx-auto">
      <div className="flex items-center gap-3 p-5 bg-marine-900 border border-marine-750 rounded-2xl shadow-hud">
        <div className="p-2.5 bg-cyan-500/20 text-cyan-400 rounded-xl">
          <HelpCircle className="w-6 h-6" />
        </div>
        <div>
          <h1 className="text-xl font-bold text-white">{t('helpPage.title', 'ORCA Maritime Platform Documentation & User Guide')}</h1>
          <p className="text-xs text-slate-400">{t('helpPage.subtitle', 'Step-by-step guidance for Potential Fishing Zones, AI Allocation, and SOS dispatch.')}</p>
        </div>
      </div>

      <SafetyDisclaimer />

      <div className="space-y-4 text-xs leading-relaxed text-slate-300">
        {/* Topic 1 */}
        <div className="marine-card rounded-2xl p-5 border border-marine-750 space-y-2">
          <h3 className="text-sm font-bold text-white flex items-center gap-2">
            <Compass className="w-4 h-4 text-cyan-400" />
            <span>1. Understanding Potential Fishing Zone (PFZ) Advisories</span>
          </h3>
          <p>
            PFZ advisories are generated by processing satellite data from ocean color sensors (Oceansat-3, MODIS) and infrared radiometers. They identify thermal gradients and chlorophyll fronts where nutrients concentrate, attracting pelagic fish shoals.
          </p>
          <ul className="list-disc pl-5 space-y-1 text-slate-400">
            <li><strong>Bearing & Direction:</strong> The compass degree from the stated landing centre.</li>
            <li><strong>Operational Depth:</strong> The recommended water depth (in meters and fathoms) for setting nets.</li>
            <li><strong>Validity:</strong> Advisories remain valid typically for 48 to 72 hours before ocean currents shift.</li>
          </ul>
        </div>

        {/* Topic 2 */}
        <div className="marine-card rounded-2xl p-5 border border-marine-750 space-y-2">
          <h3 className="text-sm font-bold text-white flex items-center gap-2">
            <Radio className="w-4 h-4 text-red-400" />
            <span>2. Agentic Emergency SOS Protocol</span>
          </h3>
          <p>
            When the Emergency SOS button is activated, your precise GPS coordinates, vessel identifier, and distress nature are automatically transmitted to:
          </p>
          <ul className="list-disc pl-5 space-y-1 text-slate-400">
            <li>State Disaster Management Authority (SDMA) Maritime Cell</li>
            <li>Nearest Indian Coast Guard Maritime Rescue Coordination Center (MRCC) via Hotline 1554</li>
            <li>Certified local field officers stationed at adjacent coastal harbours</li>
          </ul>
        </div>

        {/* Topic 3 */}
        <div className="marine-card rounded-2xl p-5 border border-marine-750 space-y-2">
          <h3 className="text-sm font-bold text-white flex items-center gap-2">
            <ShieldCheck className="w-4 h-4 text-emerald-400" />
            <span>3. Autonomous Multi-Agent Allocation Engine</span>
          </h3>
          <p>
            The allocation engine scores field agents using a multi-criteria algorithm balancing:
          </p>
          <ul className="list-disc pl-5 space-y-1 text-slate-400">
            <li><strong>Proximity:</strong> Haversine distance from the incident or fishing harbour.</li>
            <li><strong>Language:</strong> Native language fluency match for clear communication.</li>
            <li><strong>Workload:</strong> Real-time case capacity prevention of agent fatigue.</li>
            <li><strong>Skills:</strong> Specialized brevets in Marine Safety, First Aid, and GIS Navigation.</li>
          </ul>
        </div>
      </div>
    </div>
  );
};
